# Basics
add_subdirectory(basic_types)
# Data types
add_subdirectory(data_types)
# Algorithms
add_subdirectory(algorithm)
# Files
add_subdirectory(files)
# Functions
add_subdirectory(functions)
# Miscellaneous
add_subdirectory(miscellaneous)
# Networks
add_subdirectory(networks)
# Parallel
add_subdirectory(parallel)
# Utilities
add_subdirectory(utilities)
