services:
  traefik:
    image: traefik:v3.6
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy

  http-server:
    image: http-server
    build:
      context: http/src
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.http-server.rule=Host(`localhost`)
      - traefik.http.routers.http-server.entrypoints=web
      - traefik.http.services.http-server.loadbalancer.server.port=8080
    networks:
      - proxy

networks:
  proxy:
    name: proxy