[tasks.dev]
description = "Run application"
depends = ["build-cpp"]
run = "./build/app"

[tasks.build]
description = "Build application"
quiet = true
run = """
mkdir -p build
gcc -O3 src/main.c -o build/app
"""

[tasks.build-cpp]
description = "Build application"
quiet = true
run = """
mkdir -p build
g++ -O3 src/main.cpp -o build/app
"""


[tasks.clean]
description = "Clean task"
quiet = true
run = "rm -rf build"